// Auto-generated enum file - DO NOT EDIT MANUALLY
// This file is automatically generated from backend enums
// Run backend application to regenerate this file

export interface EnumItem {
  readonly value: number;
  readonly member: string;
  readonly name: string;
  readonly text: string;
  readonly class: string;
  readonly guidId: string;
}

export interface EnumCategory {
  get(value: number): EnumItem | null;
  list: EnumItem[];
}

export interface Enums {
  readonly dataStatus: DataStatusEnumCategory;
  readonly resultCode: ResultCodeEnumCategory;
}

export interface DataStatusEnumCategory extends EnumCategory {
  readonly ACTIVE: EnumItem;
  readonly INACTIVE: EnumItem;
  readonly DELETED: EnumItem;
}

export type DataStatusValue = 1 | 0 | -1;

export interface ResultCodeEnumCategory extends EnumCategory {
  readonly SUCCESS: EnumItem;
  readonly PARAMS_ERROR: EnumItem;
  readonly ERROR: EnumItem;
  readonly USER_NOT_FOUND: EnumItem;
  readonly USER_SESSION_EXPIRED: EnumItem;
  readonly USER_PERMISSION_ERROR: EnumItem;
  readonly PRODUCT_NOT_FOUND: EnumItem;
  readonly PRODUCT_ERROR: EnumItem;
  readonly RATE_LIMIT_ERROR: EnumItem;
}

export type ResultCodeValue = 200 | 4002 | 400 | 20002 | 20004 | 20005 | 11001 | 11002 | 1003;

const enumsData = {
  dataStatus: {
    ACTIVE: {
      value: 1,
      member: "ACTIVE",
      name: "",
      text: "Đang hoạt động",
      class: "",
      guidId: ""
    },
    INACTIVE: {
      value: 0,
      member: "INACTIVE",
      name: "",
      text: "Không hoạt động",
      class: "",
      guidId: ""
    },
    DELETED: {
      value: -1,
      member: "DELETED",
      name: "",
      text: "Đã xóa",
      class: "",
      guidId: ""
    },
  },
  resultCode: {
    SUCCESS: {
      value: 200,
      member: "SUCCESS",
      name: "",
      text: "Thành công",
      class: "",
      guidId: ""
    },
    PARAMS_ERROR: {
      value: 4002,
      member: "PARAMS_ERROR",
      name: "",
      text: "Tham số bất thường",
      class: "",
      guidId: ""
    },
    ERROR: {
      value: 400,
      member: "ERROR",
      name: "",
      text: "Máy chủ bận, vui lòng thử lại sau",
      class: "",
      guidId: ""
    },
    USER_NOT_FOUND: {
      value: 20002,
      member: "USER_NOT_FOUND",
      name: "",
      text: "Người dùng không tồn tại hoặc tài khoản đã bị vô hiệu hóa",
      class: "",
      guidId: ""
    },
    USER_SESSION_EXPIRED: {
      value: 20004,
      member: "USER_SESSION_EXPIRED",
      name: "",
      text: "Phiên đăng nhập của người dùng đã hết hạn, vui lòng đăng nhập lại",
      class: "",
      guidId: ""
    },
    USER_PERMISSION_ERROR: {
      value: 20005,
      member: "USER_PERMISSION_ERROR",
      name: "",
      text: "Quyền hạn không đủ",
      class: "",
      guidId: ""
    },
    PRODUCT_NOT_FOUND: {
      value: 11001,
      member: "PRODUCT_NOT_FOUND",
      name: "",
      text: "Sản phẩm không tồn tại",
      class: "",
      guidId: ""
    },
    PRODUCT_ERROR: {
      value: 11002,
      member: "PRODUCT_ERROR",
      name: "",
      text: "Sản phẩm lỗi, vui lòng thử lại sau",
      class: "",
      guidId: ""
    },
    RATE_LIMIT_ERROR: {
      value: 1003,
      member: "RATE_LIMIT_ERROR",
      name: "",
      text: "Truy cập quá thường xuyên, vui lòng thử lại sau",
      class: "",
      guidId: ""
    },
  },
} as const;

interface IEnumMember {
  value: number;
  member: string;
  name: string;
  text: string;
  class: string;
  guidId: string;
}

type IEnumCategory = Record<string, IEnumMember>;

type IProxiedEnumCategory<T extends IEnumCategory> = T & {
  get: (value: number) => IEnumMember | null;
  list: IEnumMember[];
};

type IEnums = {
  [P in keyof typeof enumsData]: IProxiedEnumCategory<typeof enumsData[P]>;
};

const createCategoryProxy = <T extends IEnumCategory>(category: T): IProxiedEnumCategory<T> => {
  return new Proxy(category, {
    get(target, prop) {
      if (prop === 'get') {
        return (value: number): IEnumMember | null => {
          for (const key in target) {
            if (target[key].value === value) {
              return target[key];
            }
          }
          return null;
        };
      }
      if (prop === 'list') {
        return Object.values(target);
      }
      return target[prop as keyof T];
    }
  }) as IProxiedEnumCategory<T>;
};

const enumData: IEnums = new Proxy(enumsData, {
  get(target, prop: string) {
    if (prop in target) {
      const categoryKey = prop as keyof typeof enumsData;
      return createCategoryProxy(target[categoryKey]);
    }
    return undefined;
  }
}) as IEnums;

export const getTextFromEnum = (list: { value: any; text: string }[], value: any) => {
  if (value === null || value === undefined) return "Chưa cập nhật";
  const item = list.find((item) => item.value === value);
  return item ? item.text : "Không xác định";
};

export const getEnumText = (enumObject: any, value: any) => {
  if (value === null || value === undefined) return 'Chưa cập nhật';
  const item = enumObject.get(value);
  return item?.text || 'Không xác định';
};

export default enumData;
