// Auto-generated enum file - DO NOT EDIT MANUALLY
// This file is automatically generated from backend enums
// Run backend application to regenerate this file

export interface EnumItem {
  readonly value: number;
  readonly member: string;
  readonly name: string;
  readonly text: string;
  readonly class: string;
  readonly guidId: string;
}

export interface EnumCategory {
  get(value: number): EnumItem | null;
  list: EnumItem[];
}

export interface Enums {
  readonly dataStatus: DataStatusEnumCategory;
  readonly resultCode: ResultCodeEnumCategory;
  readonly customerType: CustomerTypeEnumCategory;
  readonly inventoryMethod: InventoryMethodEnumCategory;
  readonly transactionType: TransactionTypeEnumCategory;
  readonly warehouseType: WarehouseTypeEnumCategory;
  readonly stockOutType: StockOutTypeEnumCategory;
  readonly stockInType: StockInTypeEnumCategory;
  readonly adjustmentType: AdjustmentTypeEnumCategory;
  readonly workflowType: WorkflowTypeEnumCategory;
  readonly workflowActionType: WorkflowActionTypeEnumCategory;
  readonly workflowStepType: WorkflowStepTypeEnumCategory;
  readonly purchaseRequisitionStatus: PurchaseRequisitionStatusEnumCategory;
  readonly rfqStatus: RfqStatusEnumCategory;
  readonly purchaseOrderStatus: PurchaseOrderStatusEnumCategory;
  readonly purchasePriority: PurchasePriorityEnumCategory;
}

export interface DataStatusEnumCategory extends EnumCategory {
  readonly ACTIVE: EnumItem;
  readonly INACTIVE: EnumItem;
  readonly DELETED: EnumItem;
}

export type DataStatusValue = 1 | 0 | -1;

export interface ResultCodeEnumCategory extends EnumCategory {
  readonly SUCCESS: EnumItem;
  readonly PARAMS_ERROR: EnumItem;
  readonly ERROR: EnumItem;
  readonly USER_NOT_FOUND: EnumItem;
  readonly USER_SESSION_EXPIRED: EnumItem;
  readonly USER_PERMISSION_ERROR: EnumItem;
  readonly PRODUCT_NOT_FOUND: EnumItem;
  readonly PRODUCT_ERROR: EnumItem;
  readonly RATE_LIMIT_ERROR: EnumItem;
}

export type ResultCodeValue = 200 | 4002 | 400 | 20002 | 20004 | 20005 | 11001 | 11002 | 1003;

export interface CustomerTypeEnumCategory extends EnumCategory {
  readonly INDIVIDUAL: EnumItem;
  readonly COMPANY: EnumItem;
}

export type CustomerTypeValue = 1 | 2;

export interface InventoryMethodEnumCategory extends EnumCategory {
  readonly FIFO: EnumItem;
  readonly LIFO: EnumItem;
}

export type InventoryMethodValue = 1 | 2;

export interface TransactionTypeEnumCategory extends EnumCategory {
  readonly STOCK_IN: EnumItem;
  readonly STOCK_OUT: EnumItem;
}

export type TransactionTypeValue = 1 | 2;

export interface WarehouseTypeEnumCategory extends EnumCategory {
  readonly CENTRAL: EnumItem;
  readonly BRANCH: EnumItem;
}

export type WarehouseTypeValue = 1 | 2;

export interface StockOutTypeEnumCategory extends EnumCategory {
  readonly INTERNAL_TRANSFER: EnumItem;
  readonly RETAIL_SALE: EnumItem;
  readonly DISPOSAL: EnumItem;
}

export type StockOutTypeValue = 1 | 2 | 3;

export interface StockInTypeEnumCategory extends EnumCategory {
  readonly EXTERNAL: EnumItem;
  readonly INTERNAL_TRANSFER: EnumItem;
}

export type StockInTypeValue = 1 | 2;

export interface AdjustmentTypeEnumCategory extends EnumCategory {
  readonly INCREASE: EnumItem;
  readonly DECREASE: EnumItem;
  readonly INVENTORY_COUNT: EnumItem;
}

export type AdjustmentTypeValue = 1 | 2 | 3;

export interface WorkflowTypeEnumCategory extends EnumCategory {
  readonly PURCHASE_REQUEST: EnumItem;
  readonly STOCK_IN_APPROVAL: EnumItem;
  readonly STOCK_OUT_REQUEST: EnumItem;
  readonly STOCK_OUT_APPROVAL: EnumItem;
  readonly ADJUSTMENT_REQUEST: EnumItem;
  readonly ADJUSTMENT_APPROVAL: EnumItem;
  readonly INVENTORY_COUNT_REQUEST: EnumItem;
  readonly INVENTORY_COUNT_APPROVAL: EnumItem;
  readonly MATERIAL_CREATION: EnumItem;
  readonly USER_PROMOTION: EnumItem;
}

export type WorkflowTypeValue = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export interface WorkflowActionTypeEnumCategory extends EnumCategory {
  readonly NEXT_STEP: EnumItem;
  readonly CONDITION: EnumItem;
  readonly END: EnumItem;
}

export type WorkflowActionTypeValue = 1 | 2 | 3;

export interface WorkflowStepTypeEnumCategory extends EnumCategory {
  readonly START_EVENT: EnumItem;
  readonly TASK: EnumItem;
  readonly GATEWAY: EnumItem;
  readonly END_EVENT: EnumItem;
}

export type WorkflowStepTypeValue = 1 | 2 | 3 | 4;

export interface PurchaseRequisitionStatusEnumCategory extends EnumCategory {
  readonly DRAFT: EnumItem;
  readonly PENDING_APPROVAL: EnumItem;
  readonly APPROVED: EnumItem;
  readonly REJECTED: EnumItem;
  readonly CONVERTED: EnumItem;
  readonly CANCELLED: EnumItem;
}

export type PurchaseRequisitionStatusValue = 1 | 2 | 3 | 4 | 5 | -1;

export interface RfqStatusEnumCategory extends EnumCategory {
  readonly DRAFT: EnumItem;
  readonly SENT: EnumItem;
  readonly RECEIVED: EnumItem;
  readonly ACCEPTED: EnumItem;
  readonly REJECTED: EnumItem;
  readonly EXPIRED: EnumItem;
  readonly CANCELLED: EnumItem;
}

export type RfqStatusValue = 1 | 2 | 3 | 4 | 5 | 6 | -1;

export interface PurchaseOrderStatusEnumCategory extends EnumCategory {
  readonly DRAFT: EnumItem;
  readonly CONFIRMED: EnumItem;
  readonly PARTIALLY_RECEIVED: EnumItem;
  readonly COMPLETED: EnumItem;
  readonly CANCELLED: EnumItem;
}

export type PurchaseOrderStatusValue = 1 | 2 | 3 | 4 | -1;

export interface PurchasePriorityEnumCategory extends EnumCategory {
  readonly LOW: EnumItem;
  readonly NORMAL: EnumItem;
  readonly HIGH: EnumItem;
  readonly URGENT: EnumItem;
}

export type PurchasePriorityValue = 1 | 2 | 3 | 4;

const enumsData = {
  dataStatus: {
    ACTIVE: {
      value: 1,
      member: "ACTIVE",
      name: "",
      text: "Đang hoạt động",
      class: "",
      guidId: ""
    },
    INACTIVE: {
      value: 0,
      member: "INACTIVE",
      name: "",
      text: "Không hoạt động",
      class: "",
      guidId: ""
    },
    DELETED: {
      value: -1,
      member: "DELETED",
      name: "",
      text: "Đã xóa",
      class: "",
      guidId: ""
    },
  },
  resultCode: {
    SUCCESS: {
      value: 200,
      member: "SUCCESS",
      name: "",
      text: "Thành công",
      class: "",
      guidId: ""
    },
    PARAMS_ERROR: {
      value: 4002,
      member: "PARAMS_ERROR",
      name: "",
      text: "Tham số bất thường",
      class: "",
      guidId: ""
    },
    ERROR: {
      value: 400,
      member: "ERROR",
      name: "",
      text: "Máy chủ bận, vui lòng thử lại sau",
      class: "",
      guidId: ""
    },
    USER_NOT_FOUND: {
      value: 20002,
      member: "USER_NOT_FOUND",
      name: "",
      text: "Người dùng không tồn tại hoặc tài khoản đã bị vô hiệu hóa",
      class: "",
      guidId: ""
    },
    USER_SESSION_EXPIRED: {
      value: 20004,
      member: "USER_SESSION_EXPIRED",
      name: "",
      text: "Phiên đăng nhập của người dùng đã hết hạn, vui lòng đăng nhập lại",
      class: "",
      guidId: ""
    },
    USER_PERMISSION_ERROR: {
      value: 20005,
      member: "USER_PERMISSION_ERROR",
      name: "",
      text: "Quyền hạn không đủ",
      class: "",
      guidId: ""
    },
    PRODUCT_NOT_FOUND: {
      value: 11001,
      member: "PRODUCT_NOT_FOUND",
      name: "",
      text: "Sản phẩm không tồn tại",
      class: "",
      guidId: ""
    },
    PRODUCT_ERROR: {
      value: 11002,
      member: "PRODUCT_ERROR",
      name: "",
      text: "Sản phẩm lỗi, vui lòng thử lại sau",
      class: "",
      guidId: ""
    },
    RATE_LIMIT_ERROR: {
      value: 1003,
      member: "RATE_LIMIT_ERROR",
      name: "",
      text: "Truy cập quá thường xuyên, vui lòng thử lại sau",
      class: "",
      guidId: ""
    },
  },
  customerType: {
    INDIVIDUAL: {
      value: 1,
      member: "INDIVIDUAL",
      name: "",
      text: "Cá nhân",
      class: "",
      guidId: ""
    },
    COMPANY: {
      value: 2,
      member: "COMPANY",
      name: "",
      text: "Doanh nghiệp",
      class: "",
      guidId: ""
    },
  },
  inventoryMethod: {
    FIFO: {
      value: 1,
      member: "FIFO",
      name: "",
      text: "FIFO - Nhập trước xuất trước",
      class: "",
      guidId: ""
    },
    LIFO: {
      value: 2,
      member: "LIFO",
      name: "",
      text: "LIFO - Nhập sau xuất trước",
      class: "",
      guidId: ""
    },
  },
  transactionType: {
    STOCK_IN: {
      value: 1,
      member: "STOCK_IN",
      name: "",
      text: "Nhập Kho",
      class: "",
      guidId: ""
    },
    STOCK_OUT: {
      value: 2,
      member: "STOCK_OUT",
      name: "",
      text: "Xuất Kho",
      class: "",
      guidId: ""
    },
  },
  warehouseType: {
    CENTRAL: {
      value: 1,
      member: "CENTRAL",
      name: "",
      text: "Kho Trung Tâm",
      class: "",
      guidId: ""
    },
    BRANCH: {
      value: 2,
      member: "BRANCH",
      name: "",
      text: "Kho Chi Nhánh",
      class: "",
      guidId: ""
    },
  },
  stockOutType: {
    INTERNAL_TRANSFER: {
      value: 1,
      member: "INTERNAL_TRANSFER",
      name: "",
      text: "Chuyển kho nội bộ",
      class: "",
      guidId: ""
    },
    RETAIL_SALE: {
      value: 2,
      member: "RETAIL_SALE",
      name: "",
      text: "Bán lẻ",
      class: "",
      guidId: ""
    },
    DISPOSAL: {
      value: 3,
      member: "DISPOSAL",
      name: "",
      text: "Tiêu hủy",
      class: "",
      guidId: ""
    },
  },
  stockInType: {
    EXTERNAL: {
      value: 1,
      member: "EXTERNAL",
      name: "",
      text: "Nhập từ nhà cung cấp",
      class: "",
      guidId: ""
    },
    INTERNAL_TRANSFER: {
      value: 2,
      member: "INTERNAL_TRANSFER",
      name: "",
      text: "Chuyển kho nội bộ",
      class: "",
      guidId: ""
    },
  },
  adjustmentType: {
    INCREASE: {
      value: 1,
      member: "INCREASE",
      name: "",
      text: "Điều chỉnh tăng",
      class: "",
      guidId: ""
    },
    DECREASE: {
      value: 2,
      member: "DECREASE",
      name: "",
      text: "Điều chỉnh giảm",
      class: "",
      guidId: ""
    },
    INVENTORY_COUNT: {
      value: 3,
      member: "INVENTORY_COUNT",
      name: "",
      text: "Kiểm kê kho",
      class: "",
      guidId: ""
    },
  },
  workflowType: {
    PURCHASE_REQUEST: {
      value: 1,
      member: "PURCHASE_REQUEST",
      name: "",
      text: "Đề nghị mua sắm",
      class: "",
      guidId: ""
    },
    STOCK_IN_APPROVAL: {
      value: 2,
      member: "STOCK_IN_APPROVAL",
      name: "",
      text: "Phê duyệt nhập kho",
      class: "",
      guidId: ""
    },
    STOCK_OUT_REQUEST: {
      value: 3,
      member: "STOCK_OUT_REQUEST",
      name: "",
      text: "Đề nghị xuất kho",
      class: "",
      guidId: ""
    },
    STOCK_OUT_APPROVAL: {
      value: 4,
      member: "STOCK_OUT_APPROVAL",
      name: "",
      text: "Phê duyệt xuất kho",
      class: "",
      guidId: ""
    },
    ADJUSTMENT_REQUEST: {
      value: 5,
      member: "ADJUSTMENT_REQUEST",
      name: "",
      text: "Đề nghị điều chỉnh kho",
      class: "",
      guidId: ""
    },
    ADJUSTMENT_APPROVAL: {
      value: 6,
      member: "ADJUSTMENT_APPROVAL",
      name: "",
      text: "Phê duyệt điều chỉnh",
      class: "",
      guidId: ""
    },
    INVENTORY_COUNT_REQUEST: {
      value: 7,
      member: "INVENTORY_COUNT_REQUEST",
      name: "",
      text: "Đề nghị kiểm kê",
      class: "",
      guidId: ""
    },
    INVENTORY_COUNT_APPROVAL: {
      value: 8,
      member: "INVENTORY_COUNT_APPROVAL",
      name: "",
      text: "Phê duyệt kiểm kê",
      class: "",
      guidId: ""
    },
    MATERIAL_CREATION: {
      value: 9,
      member: "MATERIAL_CREATION",
      name: "",
      text: "Tạo nguyên vật liệu mới",
      class: "",
      guidId: ""
    },
    USER_PROMOTION: {
      value: 10,
      member: "USER_PROMOTION",
      name: "",
      text: "Đề nghị thăng chức nhân viên",
      class: "",
      guidId: ""
    },
  },
  workflowActionType: {
    NEXT_STEP: {
      value: 1,
      member: "NEXT_STEP",
      name: "",
      text: "Chuyển bước",
      class: "",
      guidId: ""
    },
    CONDITION: {
      value: 2,
      member: "CONDITION",
      name: "",
      text: "Điều kiện",
      class: "",
      guidId: ""
    },
    END: {
      value: 3,
      member: "END",
      name: "",
      text: "Kết thúc",
      class: "",
      guidId: ""
    },
  },
  workflowStepType: {
    START_EVENT: {
      value: 1,
      member: "START_EVENT",
      name: "",
      text: "Bắt đầu",
      class: "",
      guidId: ""
    },
    TASK: {
      value: 2,
      member: "TASK",
      name: "",
      text: "Bước",
      class: "",
      guidId: ""
    },
    GATEWAY: {
      value: 3,
      member: "GATEWAY",
      name: "",
      text: "Điều kiện",
      class: "",
      guidId: ""
    },
    END_EVENT: {
      value: 4,
      member: "END_EVENT",
      name: "",
      text: "Kết thúc",
      class: "",
      guidId: ""
    },
  },
  purchaseRequisitionStatus: {
    DRAFT: {
      value: 1,
      member: "DRAFT",
      name: "",
      text: "Nháp",
      class: "",
      guidId: ""
    },
    PENDING_APPROVAL: {
      value: 2,
      member: "PENDING_APPROVAL",
      name: "",
      text: "Chờ phê duyệt",
      class: "",
      guidId: ""
    },
    APPROVED: {
      value: 3,
      member: "APPROVED",
      name: "",
      text: "Đã phê duyệt",
      class: "",
      guidId: ""
    },
    REJECTED: {
      value: 4,
      member: "REJECTED",
      name: "",
      text: "Từ chối",
      class: "",
      guidId: ""
    },
    CONVERTED: {
      value: 5,
      member: "CONVERTED",
      name: "",
      text: "Đã chuyển thành PO",
      class: "",
      guidId: ""
    },
    CANCELLED: {
      value: -1,
      member: "CANCELLED",
      name: "",
      text: "Đã hủy",
      class: "",
      guidId: ""
    },
  },
  rfqStatus: {
    DRAFT: {
      value: 1,
      member: "DRAFT",
      name: "",
      text: "Nháp",
      class: "",
      guidId: ""
    },
    SENT: {
      value: 2,
      member: "SENT",
      name: "",
      text: "Đã gửi",
      class: "",
      guidId: ""
    },
    RECEIVED: {
      value: 3,
      member: "RECEIVED",
      name: "",
      text: "Đã nhận báo giá",
      class: "",
      guidId: ""
    },
    ACCEPTED: {
      value: 4,
      member: "ACCEPTED",
      name: "",
      text: "Đã chấp nhận",
      class: "",
      guidId: ""
    },
    REJECTED: {
      value: 5,
      member: "REJECTED",
      name: "",
      text: "Từ chối",
      class: "",
      guidId: ""
    },
    EXPIRED: {
      value: 6,
      member: "EXPIRED",
      name: "",
      text: "Hết hạn",
      class: "",
      guidId: ""
    },
    CANCELLED: {
      value: -1,
      member: "CANCELLED",
      name: "",
      text: "Đã hủy",
      class: "",
      guidId: ""
    },
  },
  purchaseOrderStatus: {
    DRAFT: {
      value: 1,
      member: "DRAFT",
      name: "",
      text: "Nháp",
      class: "",
      guidId: ""
    },
    CONFIRMED: {
      value: 2,
      member: "CONFIRMED",
      name: "",
      text: "Đã xác nhận",
      class: "",
      guidId: ""
    },
    PARTIALLY_RECEIVED: {
      value: 3,
      member: "PARTIALLY_RECEIVED",
      name: "",
      text: "Nhận một phần",
      class: "",
      guidId: ""
    },
    COMPLETED: {
      value: 4,
      member: "COMPLETED",
      name: "",
      text: "Hoàn thành",
      class: "",
      guidId: ""
    },
    CANCELLED: {
      value: -1,
      member: "CANCELLED",
      name: "",
      text: "Đã hủy",
      class: "",
      guidId: ""
    },
  },
  purchasePriority: {
    LOW: {
      value: 1,
      member: "LOW",
      name: "",
      text: "Thấp",
      class: "",
      guidId: ""
    },
    NORMAL: {
      value: 2,
      member: "NORMAL",
      name: "",
      text: "Bình thường",
      class: "",
      guidId: ""
    },
    HIGH: {
      value: 3,
      member: "HIGH",
      name: "",
      text: "Cao",
      class: "",
      guidId: ""
    },
    URGENT: {
      value: 4,
      member: "URGENT",
      name: "",
      text: "Khẩn cấp",
      class: "",
      guidId: ""
    },
  },
} as const;

interface IEnumMember {
  value: number;
  member: string;
  name: string;
  text: string;
  class: string;
  guidId: string;
}

type IEnumCategory = Record<string, IEnumMember>;

type IProxiedEnumCategory<T extends IEnumCategory> = T & {
  get: (value: number) => IEnumMember | null;
  list: IEnumMember[];
};

type IEnums = {
  [P in keyof typeof enumsData]: IProxiedEnumCategory<typeof enumsData[P]>;
};

const createCategoryProxy = <T extends IEnumCategory>(category: T): IProxiedEnumCategory<T> => {
  return new Proxy(category, {
    get(target, prop) {
      if (prop === 'get') {
        return (value: number): IEnumMember | null => {
          for (const key in target) {
            if (target[key].value === value) {
              return target[key];
            }
          }
          return null;
        };
      }
      if (prop === 'list') {
        return Object.values(target);
      }
      return target[prop as keyof T];
    }
  }) as IProxiedEnumCategory<T>;
};

const enumData: IEnums = new Proxy(enumsData, {
  get(target, prop: string) {
    if (prop in target) {
      const categoryKey = prop as keyof typeof enumsData;
      return createCategoryProxy(target[categoryKey]);
    }
    return undefined;
  }
}) as IEnums;

export const getTextFromEnum = (list: { value: any; text: string }[], value: any) => {
  if (value === null || value === undefined) return "Chưa cập nhật";
  const item = list.find((item) => item.value === value);
  return item ? item.text : "Không xác định";
};

export const getEnumText = (enumObject: any, value: any) => {
  if (value === null || value === undefined) return 'Chưa cập nhật';
  const item = enumObject.get(value);
  return item?.text || 'Không xác định';
};

export default enumData;
